# Generated by Django 4.2.21 on 2025-07-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followers', 'following')},
        ),
    ]
