# Generated by Django 4.2.23 on 2025-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_googleoauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
