# Generated by Django 4.2.23 on 2025-09-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_is_user_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
